name: Deploy Mstore Api

defaults:
  run:
    working-directory: mstore-api

on:
  push:
    branches:
      - main
    paths:
      - 'mstore-api/**'
      - '.github/workflows/deploy-mstore-api.yaml'

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
      commitMsg: ${{ github.event.commits[0].message }}
      userId: ${{ secrets.USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mstore-api"
          file: Dockerfile
          push: true
          tags: devaprakash/mstore-api:latest
          build-args: |
            "mongoURI=${{ env.mongoURI }}"
            "mongoDatabase=${{ env.mongoDatabase }}"
      - name: Webhook
        uses: distributhor/workflow-webhook
        with:
        url: "http://ci.deva-prakash.tech/hooks/deploy-mstore-app?userId=${{env.userId}}&msg=${{env.commitMsg}}"