name: Deploy Mstore App

defaults:
  run:
    working-directory: mstore-app

on:
  workflow_dispatch:

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
      userId: ${{ secrets.USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: "http://ci.deva-prakash.tech/hooks/deploy-mstore-app"
          data: '{ "userId": "${{env.userId}}" }'