name: Deploy Mstore Api

defaults:
  run:
    working-directory: mstore-api

on:
  push:
    branches:
      - main
    paths:
      - 'mstore-api/**'
      - '.github/workflows/deploy-mstore-api.yaml'

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devaprakash/mstore-api:latest