name: Deploy Mstore Api

on:
  push:
    branches:
      - main
    paths:
      - 'mstore-api/**'
      - '.github/workflows/deploy-mstore-api.yaml'

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
    steps:
      - run: ls
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: devaprakash/mstore-api:latest