name: Deploy Mstore Api

defaults:
  run:
    working-directory: mstore-api

on:
  push:
    branches:
      - main
    paths:
      - 'mstore-api/**'
      - '.github/workflows/deploy-mstore-api.yaml'

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build --build-arg mongoURI=${{ secrets.mongoURI }} --build-arg mongoDatabase=${{ secrets.mongoDatabase }} -t devaprakash/mstore-api .
      - run: docker push devaprakash/mstore-api