name: Deploy Mstore App

defaults:
  run:
    working-directory: mstore-app

on:
  push:
    branches:
      - main
    paths:
      - 'mstore-app/**'
      - '.github/workflows/deploy-mstore-app.yaml'

jobs:
      
  build:
    runs-on: ubuntu-latest
    env:
      mongoURI: ${{ secrets.mongoURI }}
      mongoDatabase: ${{ secrets.mongoDatabase }}
      commitMsg: ${{  github.event.head_commit.message }}
      userId: ${{ secrets.USER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:mstore-app"
          file: Dockerfile
          push: true
          tags: devaprakash/mstore-app:latest
          build-args: |
            "mongoURI=${{ env.mongoURI }}"
            "mongoDatabase=${{ env.mongoDatabase }}"
      - name: Webhook
        uses: distributhor/workflow-webhook@v3
        env:
          webhook_url: "http://ci.deva-prakash.tech/hooks/deploy-mstore-app"
          data: '{ "userId": "${{env.userId}}", "msg" : "${{env.commitMsg}}" }'